//! Sandbox testing utilities for NEAR Protocol.
//!
//! This crate provides ergonomic APIs for testing against a local NEAR sandbox.
//! It handles sandbox lifecycle management, including shared singleton instances
//! for test performance and fresh instances for isolated tests.
//!
//! The sandbox runs as a Docker container via testcontainers, using the
//! `nearprotocol/sandbox` image from Docker Hub.
//!
//! # Design Principles
//!
//! 1. **Consistent with production**: Test code looks like production code.
//!    `Near` is always the entry point - you just pass a different network.
//!
//! 2. **Sandbox lifecycle management**: The library handles starting/stopping
//!    sandboxes, including a shared singleton for test performance.
//!
//! 3. **No magic account creation**: All accounts are created through the
//!    standard `near.transaction().create_account()` flow.
//!
//! # Example
//!
//! ```rust,ignore
//! use near_kit::{NearToken, signer::SecretKey};
//! use near_kit_sandbox::SandboxConfig;
//!
//! #[tokio::test]
//! async fn test_transfer() -> Result<(), Box<dyn std::error::Error>> {
//!     // Same pattern as production - just different network
//!     let near = SandboxConfig::shared().await?.client();
//!
//!     // Create accounts the normal way
//!     let alice_key = SecretKey::generate_ed25519();
//!     near.transaction("alice.sandbox")
//!         .create_account()
//!         .transfer("100 NEAR")
//!         .add_full_access_key(alice_key.public_key())
//!         .send()
//!         .await?;
//!     Ok(())
//! }
//!
//! #[tokio::test]
//! async fn test_isolated() -> Result<(), Box<dyn std::error::Error>> {
//!     // Fresh sandbox - completely isolated, stopped when container drops
//!     let sandbox = SandboxConfig::fresh().await?;
//!     let near = sandbox.client();
//!     Ok(())
//! }
//!
//! #[tokio::test]
//! async fn test_custom_version() -> Result<(), Box<dyn std::error::Error>> {
//!     // Specific sandbox version
//!     let sandbox = SandboxConfig::builder()
//!         .version("2.10.5")
//!         .fresh()
//!         .await?;
//!     let near = sandbox.client();
//!     Ok(())
//! }
//!
//! #[tokio::test]
//! async fn test_custom_root() -> Result<(), Box<dyn std::error::Error>> {
//!     // Custom root account name
//!     let sandbox = SandboxConfig::builder()
//!         .root_account("sb")
//!         .fresh()
//!         .await?;
//!     let near = sandbox.client();
//!     // Root account is now "sb" instead of "sandbox"
//!     Ok(())
//! }
//! ```

use std::borrow::Cow;
use std::sync::Arc;
use std::time::Duration;

use near_kit::protocol::{ChainId, ParseAccountIdError, TryIntoAccountId};
use near_kit::rpc::{RpcError, SandboxNetwork};
use near_kit::signer::{InMemorySigner, Signer};
use near_kit::{AccountId, Error, Near, NearToken};
use testcontainers::{
    ContainerAsync, CopyToContainer, Healthcheck, Image, ImageExt,
    core::{ContainerPort, WaitFor},
    runners::AsyncRunner,
};
use thiserror::Error as ThisError;
use tokio::sync::OnceCell;

#[cfg(feature = "tracing")]
use tracing::info;

#[cfg(not(feature = "tracing"))]
macro_rules! info {
    ($($arg:tt)*) => {};
}

/// Default sandbox root account ID.
pub const SANDBOX_ROOT_ACCOUNT: &str = "sandbox";

/// Default sandbox root secret key.
///
/// This deterministic key is generated by `near-sandbox init --test-seed sandbox`.
pub const SANDBOX_ROOT_SECRET_KEY: &str = "ed25519:3JoAjwLppjgvxkk6kNsu5wQj3FfUJnpBKWieC73hVTpBeA6FZiCc5tfyZL3a3tHeQJegQe4qGSv8FLsYp7TYd1r6";

/// Failure while validating sandbox configuration or starting its container.
#[derive(Debug, ThisError)]
pub enum SandboxError {
    /// The configured root account is not a valid NEAR account ID.
    #[error("invalid sandbox root account: {0}")]
    InvalidRootAccount(#[source] ParseAccountIdError),

    /// An account passed to a sandbox helper is not a valid NEAR account ID.
    #[error("invalid sandbox account: {0}")]
    InvalidAccount(#[from] ParseAccountIdError),

    /// The requested chain ID is reserved for a public network.
    #[error("sandbox chain ID {0:?} is reserved by neard; use a custom ID such as \"localnet\"")]
    UnsupportedChainId(String),

    /// The deterministic sandbox root signer could not be constructed.
    #[error("failed to construct the sandbox root signer: {0}")]
    RootSigner(#[source] Error),

    /// Docker or testcontainers failed while preparing the sandbox.
    #[error("sandbox container {operation} failed: {message}")]
    Container {
        /// The container operation that failed.
        operation: &'static str,
        /// The underlying error message.
        message: String,
    },

    /// A sandbox-specific RPC request failed.
    #[error("sandbox RPC request failed: {0}")]
    Rpc(#[source] Box<RpcError>),

    /// A patched account balance did not become observable within the retry budget.
    #[error("sandbox balance patch for {account_id} was not observable after {attempts} attempts")]
    PatchTimeout {
        /// The account whose patched balance was not observed.
        account_id: AccountId,
        /// Number of observation attempts made.
        attempts: u32,
        /// Last client error observed while polling, if any.
        #[source]
        last_error: Option<Box<Error>>,
    },
}

impl From<RpcError> for SandboxError {
    fn from(error: RpcError) -> Self {
        Self::Rpc(Box::new(error))
    }
}

// ============================================================================
// NearSandbox testcontainers Image (inlined from near-sandbox-testcontainer)
// ============================================================================

const DEFAULT_IMAGE: &str = "nearprotocol/sandbox";
// Pin ordinary integration tests to a stable 2.13 release.
const DEFAULT_VERSION: &str = "2.13.4";

/// The RPC port exposed by the NEAR sandbox container.
const RPC_PORT: ContainerPort = ContainerPort::Tcp(3030);

/// Grace period before Docker starts counting failed healthcheck probes.
///
/// The image's own healthcheck (10s start period, 5s interval, 3 retries)
/// flips the container to `unhealthy` after roughly 25–30s without a
/// successful `/status` probe. That is too tight on a loaded Docker host —
/// e.g. several sandbox suites starting containers at once — where neard can
/// take longer than that just to initialize, and testcontainers then fails the
/// start. A successful probe still marks the container healthy immediately, so
/// a longer grace period only delays reporting a node that never comes up.
/// The probe command, interval and retries are inherited from the image.
const HEALTHCHECK_START_PERIOD: Duration = Duration::from_secs(90);

/// Overall budget for the container to become healthy (testcontainers defaults
/// to 60s). Kept above [`HEALTHCHECK_START_PERIOD`] plus the image's
/// `retries × interval` so a node that never comes up is reported as
/// `Unhealthy` rather than as a bare startup timeout.
const STARTUP_TIMEOUT: Duration = Duration::from_secs(120);

/// A [`testcontainers::Image`] for the NEAR sandbox Docker image
/// (`nearprotocol/sandbox`).
///
/// Configuration is passed via environment variables supported by the
/// image's entrypoint (`NEAR_ROOT_ACCOUNT`, `NEAR_CHAIN_ID`,
/// `NEAR_ENABLE_SANDBOX_LOG`).
///
/// The image name and tag can be overridden via the `NEAR_SANDBOX_IMAGE`
/// environment variable (e.g. `NEAR_SANDBOX_IMAGE=my-registry/sandbox:custom`).
/// The value is split on the last `:` into image name and tag (`name[:tag]`).
/// If no `:` is present, the value is used as the image name with the default tag.
///
/// The image must define a Docker `HEALTHCHECK` for readiness detection.
#[derive(Debug, Clone)]
struct NearSandbox {
    image_name: String,
    tag: String,
    env_vars: Vec<(String, String)>,
    copy_to_sources: Vec<CopyToContainer>,
}

impl NearSandbox {
    /// Creates a new [`NearSandbox`] image with the given version tag.
    ///
    /// The image name and tag can be overridden by setting the
    /// `NEAR_SANDBOX_IMAGE` environment variable (e.g.
    /// `my-registry/sandbox:custom`).
    fn new(version: &str) -> Self {
        let (image_name, tag) = match std::env::var("NEAR_SANDBOX_IMAGE") {
            Ok(raw) => {
                let val = raw.trim();
                if val.is_empty() {
                    (DEFAULT_IMAGE.to_owned(), version.to_owned())
                } else {
                    match val.rsplit_once(':') {
                        Some((name, tag)) if !name.is_empty() && !tag.is_empty() => {
                            (name.to_owned(), tag.to_owned())
                        }
                        _ => (val.to_owned(), version.to_owned()),
                    }
                }
            }
            Err(_) => (DEFAULT_IMAGE.to_owned(), version.to_owned()),
        };

        Self {
            image_name,
            tag,
            env_vars: vec![
                // Enable sandbox logging for easier debugging
                ("NEAR_ENABLE_SANDBOX_LOG".to_owned(), "1".to_owned()),
            ],
            copy_to_sources: Vec::new(),
        }
    }

    fn with_account_id(mut self, account_id: impl Into<String>) -> Self {
        self.env_vars
            .push(("NEAR_ROOT_ACCOUNT".to_owned(), account_id.into()));
        self
    }

    fn with_chain_id(mut self, chain_id: impl Into<String>) -> Self {
        self.env_vars
            .push(("NEAR_CHAIN_ID".to_owned(), chain_id.into()));
        self
    }
}

impl Default for NearSandbox {
    fn default() -> Self {
        Self::new(DEFAULT_VERSION)
    }
}

impl Image for NearSandbox {
    fn name(&self) -> &str {
        &self.image_name
    }

    fn tag(&self) -> &str {
        &self.tag
    }

    fn ready_conditions(&self) -> Vec<WaitFor> {
        vec![WaitFor::healthcheck()]
    }

    fn env_vars(
        &self,
    ) -> impl IntoIterator<Item = (impl Into<Cow<'_, str>>, impl Into<Cow<'_, str>>)> {
        self.env_vars.iter().map(|(k, v)| (k.as_str(), v.as_str()))
    }

    fn copy_to_sources(&self) -> impl IntoIterator<Item = &CopyToContainer> {
        &self.copy_to_sources
    }

    fn expose_ports(&self) -> &[ContainerPort] {
        &[RPC_PORT]
    }
}

// ============================================================================
// Global shared sandbox
// ============================================================================

/// Global shared sandbox instance.
static SHARED_SANDBOX: OnceCell<Sandbox> = OnceCell::const_new();

/// Remove the shared sandbox container on normal process exit.
///
/// Statics are never dropped in Rust, so the watchdog (which handles signals)
/// won't cover normal process exit. This `atexit` handler ensures the container
/// is cleaned up on clean termination.
///
/// We must NOT use tokio/async here: by the time `atexit` fires the main
/// thread's TLS (including tokio's) is destroyed, and reusing the async Docker
/// client panics with a TLS `AccessError`. Such a panic inside this
/// non-unwinding `extern "C"` fn would abort the process, so we shell out to
/// `docker rm` (which touches no Rust/tokio TLS) and wrap the body in
/// `catch_unwind` as a belt-and-suspenders guard against any unwind crossing
/// the C boundary. Removal is best-effort and errors are ignored; the
/// testcontainers watchdog still covers signal-based termination (Ctrl+C etc.).
extern "C" fn cleanup_shared_sandbox() {
    let _ = std::panic::catch_unwind(|| {
        if let Some(sandbox) = SHARED_SANDBOX.get() {
            // `OnceCell::get` on a `tokio::sync::OnceCell` is a non-async atomic
            // check, so it is safe to call from an `atexit` handler.
            let _ = std::process::Command::new("docker")
                .args(["rm", "-f", "-v", &sandbox.container_id])
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .status();
        }
    });
}

/// Register atexit handler for shared sandbox cleanup.
fn register_shared_cleanup() {
    unsafe {
        libc::atexit(cleanup_shared_sandbox);
    }
}

// ============================================================================
// Sandbox
// ============================================================================

/// A sandbox instance backed by a Docker container via testcontainers.
///
/// Cloning a `Sandbox` shares the underlying container — the container is stopped
/// only when the last `Arc` reference is dropped.
///
/// Obtain one via [`SandboxConfig::shared()`] (global singleton) or
/// [`SandboxConfig::fresh()`] (new isolated instance).
///
/// # Cleanup
///
/// - **Fresh sandboxes**: cleaned up via testcontainers' `Drop` impl.
/// - **Shared sandbox**: cleaned up via an `atexit` handler that synchronously
///   shells out to `docker rm -f` by container id (normal exit; no tokio/async)
///   and the testcontainers `watchdog` (SIGINT/SIGTERM/SIGQUIT, e.g. Ctrl+C).
#[derive(Clone)]
pub struct Sandbox {
    #[allow(dead_code)]
    container: Arc<ContainerAsync<NearSandbox>>,
    /// Docker container id, captured at start so the `atexit` handler can remove
    /// the shared container synchronously without touching the async client.
    container_id: String,
    rpc_url: String,
    root_account: AccountId,
    chain_id: ChainId,
    root_signer: Arc<dyn Signer>,
}

impl Sandbox {
    async fn start(
        version: &str,
        root_account: AccountId,
        chain_id: Option<ChainId>,
    ) -> Result<Self, SandboxError> {
        info!(
            version = version,
            root_account = %root_account,
            chain_id = chain_id.as_ref().map(ChainId::as_str).unwrap_or("(default)"),
            "Starting sandbox container"
        );

        let root_signer = Arc::new(
            InMemorySigner::new(&root_account, SANDBOX_ROOT_SECRET_KEY)
                .map_err(SandboxError::RootSigner)?,
        );
        let mut image = NearSandbox::new(version).with_account_id(root_account.to_string());
        if let Some(ref id) = chain_id {
            image = image.with_chain_id(id.to_string());
        }
        let container = image
            .with_health_check(Healthcheck::empty().with_start_period(HEALTHCHECK_START_PERIOD))
            .with_startup_timeout(STARTUP_TIMEOUT)
            .start()
            .await
            .map_err(|error| SandboxError::Container {
                operation: "start",
                message: error.to_string(),
            })?;
        let container_id = container.id().to_string();

        let host = container
            .get_host()
            .await
            .map_err(|error| SandboxError::Container {
                operation: "host discovery",
                message: error.to_string(),
            })?;

        let host_port = container
            .get_host_port_ipv4(RPC_PORT)
            .await
            .map_err(|error| SandboxError::Container {
                operation: "RPC port discovery",
                message: error.to_string(),
            })?;

        let rpc_url = format!("http://{}:{}", host, host_port);

        info!(rpc_url = %rpc_url, "Sandbox container ready");

        Ok(Self {
            container: Arc::new(container),
            container_id,
            rpc_url,
            root_account,
            chain_id: chain_id.unwrap_or_else(|| ChainId::new("sandbox")),
            root_signer,
        })
    }

    /// Get a configured `Near` client for this sandbox.
    ///
    /// This is a convenience method equivalent to `Near::sandbox(self)`.
    pub fn client(&self) -> Near {
        Near::sandbox(self)
    }

    /// Return the sandbox RPC URL.
    pub fn rpc_url(&self) -> &str {
        &self.rpc_url
    }

    /// Return the configured root account ID.
    pub fn root_account_id(&self) -> &AccountId {
        &self.root_account
    }

    /// Return the sandbox chain ID.
    pub fn chain_id(&self) -> &ChainId {
        &self.chain_id
    }

    /// Return the stable root signer used by [`Sandbox::client`].
    ///
    /// This only clones an [`Arc`]; it does not claim or rotate a signing key.
    pub fn root_signer(&self) -> Arc<dyn Signer> {
        self.root_signer.clone()
    }

    /// Set an account's balance in this sandbox.
    ///
    /// This patches the account's balance directly via the sandbox RPC,
    /// useful for testing scenarios that require specific balances
    /// (e.g., staking tests that need 1M+ NEAR).
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// use near_kit::{NearToken};
    /// use near_kit_sandbox::SandboxConfig;
    ///
    /// let sandbox = SandboxConfig::shared().await?;
    ///
    /// // Set account balance to 1M NEAR for staking test
    /// sandbox.set_balance("validator.sandbox", NearToken::from_near(1_000_000)).await?;
    /// ```
    pub async fn set_balance(
        &self,
        account_id: impl TryIntoAccountId,
        balance: NearToken,
    ) -> Result<(), SandboxError> {
        let near = self.client();
        let account_id = account_id.try_into_account_id()?;

        // Fetch raw account data from RPC - this includes all fields the sandbox expects
        let mut account_response: serde_json::Value = near
            .rpc()
            .call(
                "query",
                serde_json::json!({
                    "finality": "optimistic",
                    "request_type": "view_account",
                    "account_id": account_id.to_string()
                }),
            )
            .await?;

        // Modify the amount field in the response
        if let Some(obj) = account_response.as_object_mut() {
            obj.insert(
                "amount".to_string(),
                serde_json::Value::String(balance.as_yoctonear().to_string()),
            );
        }

        let records = serde_json::json!([
            {
                "Account": {
                    "account_id": account_id.to_string(),
                    "account": account_response
                }
            }
        ]);

        near.rpc().sandbox_patch_state(records).await?;

        // `sandbox_patch_state` applies asynchronously and is racy (see the note
        // in `RpcClient::sandbox_patch_state`). Rather than trust a fixed delay,
        // poll until the new balance is observable so callers can read it back
        // immediately. Bounded so a genuinely failed patch still returns.
        const OBSERVATION_ATTEMPTS: u32 = 50;
        let mut last_error = None;
        for _ in 0..OBSERVATION_ATTEMPTS {
            match near.account(&account_id).await {
                Ok(account) if account.amount == balance => return Ok(()),
                Ok(_) => {}
                Err(error) => last_error = Some(Box::new(error)),
            }
            tokio::time::sleep(std::time::Duration::from_millis(100)).await;
        }

        Err(SandboxError::PatchTimeout {
            account_id,
            attempts: OBSERVATION_ATTEMPTS,
            last_error,
        })
    }

    /// Fast-forward the sandbox by `delta_height` blocks.
    ///
    /// Useful for testing time-dependent logic (e.g., lockups, staking epoch
    /// changes) without waiting for real block production.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// use near_kit_sandbox::SandboxConfig;
    ///
    /// let sandbox = SandboxConfig::shared().await?;
    /// sandbox.fast_forward(1000).await?;
    /// ```
    pub async fn fast_forward(&self, delta_height: u64) -> Result<(), SandboxError> {
        self.client()
            .rpc()
            .sandbox_fast_forward(delta_height)
            .await?;
        Ok(())
    }
}

impl SandboxNetwork for Sandbox {
    fn rpc_url(&self) -> &str {
        self.rpc_url()
    }

    fn chain_id(&self) -> &ChainId {
        self.chain_id()
    }

    fn root_signer(&self) -> Arc<dyn Signer> {
        self.root_signer()
    }
}

// ============================================================================
// SandboxConfig
// ============================================================================

/// Configuration and factory for sandbox instances.
///
/// Provides two main ways to get a sandbox:
/// - [`SandboxConfig::shared()`] - Returns a reference to a global singleton sandbox
/// - [`SandboxConfig::fresh()`] - Spawns a new sandbox that is stopped when the last clone drops
///
/// For custom configuration (e.g., specific version or root account), use [`SandboxConfig::builder()`].
///
/// # Example
///
/// ```rust,ignore
/// use near_kit_sandbox::SandboxConfig;
///
/// #[tokio::test]
/// async fn test_shared() -> Result<(), Box<dyn std::error::Error>> {
///     // Fast - reuses existing sandbox
///     let near = SandboxConfig::shared().await?.client();
///     Ok(())
/// }
///
/// #[tokio::test]
/// async fn test_fresh() -> Result<(), Box<dyn std::error::Error>> {
///     // Isolated - gets its own sandbox
///     let sandbox = SandboxConfig::fresh().await?;
///     let near = sandbox.client();
///     Ok(())
/// }
///
/// #[tokio::test]
/// async fn test_custom_version() -> Result<(), Box<dyn std::error::Error>> {
///     let sandbox = SandboxConfig::builder()
///         .version("2.10.5")
///         .fresh()
///         .await?;
///     let near = sandbox.client();
///     Ok(())
/// }
/// ```
pub struct SandboxConfig;

impl SandboxConfig {
    /// Get a reference to the global shared sandbox.
    ///
    /// The first call will start the sandbox; subsequent calls return
    /// the same instance. This is ideal for most tests where you don't
    /// need completely fresh blockchain state.
    ///
    /// The shared sandbox is never stopped - it persists for the entire
    /// test run.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let near = SandboxConfig::shared().await?.client();
    /// ```
    pub async fn shared() -> Result<&'static Sandbox, SandboxError> {
        SandboxBuilder::new().shared().await
    }

    /// Spawn a fresh sandbox instance.
    ///
    /// Creates a new sandbox with clean state. The sandbox container will be
    /// stopped and cleaned up when the last clone of the returned [`Sandbox`]
    /// is dropped.
    ///
    /// Use this for tests that need guaranteed isolation from other tests.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let sandbox = SandboxConfig::fresh().await?;
    /// let near = sandbox.client();
    /// // sandbox is stopped when last reference goes out of scope
    /// ```
    pub async fn fresh() -> Result<Sandbox, SandboxError> {
        SandboxBuilder::new().fresh().await
    }

    /// Create a builder for custom sandbox configuration.
    ///
    /// Use this when you need to specify a particular sandbox version
    /// or custom root account name.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let sandbox = SandboxConfig::builder()
    ///     .version("2.10.5")
    ///     .root_account("sb")
    ///     .fresh()
    ///     .await?;
    /// ```
    pub fn builder() -> SandboxBuilder {
        SandboxBuilder::new()
    }
}

// ============================================================================
// SandboxBuilder
// ============================================================================

/// Builder for custom sandbox configuration.
///
/// Created via [`SandboxConfig::builder()`].
pub struct SandboxBuilder {
    version: Option<String>,
    root_account: Option<AccountId>,
    chain_id: Option<ChainId>,
    construction_error: Option<SandboxError>,
}

impl SandboxBuilder {
    fn new() -> Self {
        Self {
            version: None,
            root_account: None,
            chain_id: None,
            construction_error: None,
        }
    }

    fn record_error(&mut self, error: SandboxError) {
        if self.construction_error.is_none() {
            self.construction_error = Some(error);
        }
    }

    fn resolve(self) -> Result<ResolvedSandboxConfig, SandboxError> {
        if let Some(error) = self.construction_error {
            return Err(error);
        }

        let root_account = match self.root_account {
            Some(account_id) => account_id,
            None => SANDBOX_ROOT_ACCOUNT
                .try_into_account_id()
                .map_err(SandboxError::InvalidRootAccount)?,
        };

        Ok(ResolvedSandboxConfig {
            version: self.version.unwrap_or_else(|| DEFAULT_VERSION.to_string()),
            root_account,
            chain_id: self.chain_id,
        })
    }

    /// Set the sandbox version to use.
    ///
    /// If not specified, uses the bundled default nearcore version.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let sandbox = SandboxConfig::builder()
    ///     .version("2.10.5")
    ///     .fresh()
    ///     .await?;
    /// ```
    pub fn version(mut self, version: impl Into<String>) -> Self {
        self.version = Some(version.into());
        self
    }

    /// Set the root account name for this sandbox.
    ///
    /// If not specified, defaults to `"sandbox"`.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let sandbox = SandboxConfig::builder()
    ///     .root_account("sb")
    ///     .fresh()
    ///     .await?;
    /// // Sub-accounts will be "alice.sb" instead of "alice.sandbox"
    /// ```
    pub fn root_account(mut self, name: impl TryIntoAccountId) -> Self {
        match name.try_into_account_id() {
            Ok(account_id) => self.root_account = Some(account_id),
            Err(error) => self.record_error(SandboxError::InvalidRootAccount(error)),
        }
        self
    }

    /// Set the chain ID for this sandbox.
    ///
    /// Useful for testing chain-ID-dependent logic (e.g., signed wallet
    /// requests that compare against the chain ID).
    ///
    /// If not specified, the sandbox uses its default chain ID.
    ///
    /// **Note:** `"mainnet"` and `"testnet"` are not supported. Attempting to
    /// use either is reported by [`SandboxBuilder::fresh`] or
    /// [`SandboxBuilder::shared`].
    /// `neard` reserves these chain IDs for the real networks and rejects the
    /// sandbox test-seed during `init`, so the container never passes its
    /// health check (surfacing only as an opaque container-startup failure).
    /// Use a custom chain ID instead (e.g. `"localnet"`, or `"pinet"` for
    /// Private Shard).
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let sandbox = SandboxConfig::builder()
    ///     .chain_id("localnet")
    ///     .fresh()
    ///     .await?;
    /// ```
    pub fn chain_id(mut self, chain_id: impl Into<String>) -> Self {
        let chain_id = chain_id.into();
        if matches!(chain_id.as_str(), "mainnet" | "testnet") {
            self.record_error(SandboxError::UnsupportedChainId(chain_id));
        } else {
            self.chain_id = Some(ChainId::new(chain_id));
        }
        self
    }

    /// Spawn a fresh sandbox with the configured options.
    ///
    /// The sandbox container will be stopped when the last clone of
    /// the returned [`Sandbox`] is dropped.
    pub async fn fresh(self) -> Result<Sandbox, SandboxError> {
        let config = self.resolve()?;
        Sandbox::start(&config.version, config.root_account, config.chain_id).await
    }

    /// Get or create the shared sandbox with the configured options.
    ///
    /// **Note:** The version, root account, and chain ID are only used if the
    /// shared sandbox hasn't been initialized yet. If it's already running, the
    /// existing instance is returned regardless of the options specified here.
    pub async fn shared(self) -> Result<&'static Sandbox, SandboxError> {
        let config = self.resolve()?;
        SHARED_SANDBOX
            .get_or_try_init(|| async move {
                let sandbox =
                    Sandbox::start(&config.version, config.root_account, config.chain_id).await?;
                register_shared_cleanup();
                Ok(sandbox)
            })
            .await
    }
}

struct ResolvedSandboxConfig {
    version: String,
    root_account: AccountId,
    chain_id: Option<ChainId>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chain_id_mainnet_is_deferred_as_an_error() {
        let result = SandboxConfig::builder().chain_id("mainnet").resolve();
        assert!(matches!(
            result,
            Err(SandboxError::UnsupportedChainId(chain_id)) if chain_id == "mainnet"
        ));
    }

    #[test]
    fn invalid_root_account_is_deferred_as_an_error() {
        let result = SandboxConfig::builder().root_account("INVALID").resolve();
        assert!(matches!(result, Err(SandboxError::InvalidRootAccount(_))));
    }

    #[test]
    fn chain_id_custom_is_accepted() {
        let config = SandboxConfig::builder()
            .chain_id("localnet")
            .resolve()
            .unwrap();
        assert_eq!(
            config.chain_id.as_ref().map(ChainId::as_str),
            Some("localnet")
        );
    }

    #[test]
    fn builder_preserves_the_first_construction_error() {
        let result = SandboxConfig::builder()
            .root_account("INVALID")
            .chain_id("mainnet")
            .resolve();
        assert!(matches!(result, Err(SandboxError::InvalidRootAccount(_))));
    }
}
